/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sando
 */
public class ConsultasForm extends javax.swing.JFrame {

    /**
     * Creates new form ConsultasForm
     */
    public ConsultasForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelConsultarRegistros = new javax.swing.JLabel();
        jTextFieldBuscarPorID = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonExportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFondoTaladro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelConsultarRegistros.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelConsultarRegistros.setText("Consultar Registros");
        jPanel1.add(jLabelConsultarRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));

        jTextFieldBuscarPorID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldBuscarPorID.setText("Buscar por ID...");
        jTextFieldBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarPorIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscarPorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 140, 40));

        jButtonExportar.setBackground(new java.awt.Color(0, 204, 0));
        jButtonExportar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonExportar.setText("Exportar");
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"28/03/2025", "06:00", "14:00", "Pedro Perez", "Aprendiz", null},
                {"28/03/2025", "06:00", "14:00", "Pablo Rodriguez", "Visitante", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Juan Perez", "Funcionario", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Pedro Perez", "Aprendiz", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Pablo Rodriguez", "Visitante", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Juan Perez", "Funcionario", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Pedro Perez", "Aprendiz", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Pablo Rodriguez", "Visitante", "S/N"},
                {"28/03/2025", "06:00", "14:00", "Juan Perez", "Funcionario", "S/N"},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha ", "Entrada", "Salida", "Persona", "Cargo", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 110, 760, -1));

        jLabelFondoTaladro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taladro.jpg"))); // NOI18N
        jLabelFondoTaladro.setText("jLabel1");
        jPanel1.add(jLabelFondoTaladro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarPorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarPorIDActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
    
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsultasForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JLabel jLabelConsultarRegistros;
    private javax.swing.JLabel jLabelFondoTaladro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscarPorID;
    // End of variables declaration//GEN-END:variables
}
