/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author sando
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelControlAcceso = new javax.swing.JLabel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldIngresarUsuario = new javax.swing.JTextField();
        jLabelConstraseña = new javax.swing.JLabel();
        jPasswordIngresarContraseña = new javax.swing.JPasswordField();
        jButtonAcceder = new javax.swing.JButton();
        jLabelFondoTaladro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 623, -1, -1));

        jLabelControlAcceso.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelControlAcceso.setText("Control Acceso Porteria");
        getContentPane().add(jLabelControlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabelBienvenido.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelBienvenido.setText("Bienvenido");
        getContentPane().add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jTextFieldIngresarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldIngresarUsuario.setText("Ingrese su usuario");
        jTextFieldIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, -1));

        jLabelConstraseña.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelConstraseña.setText("Contraseña");
        getContentPane().add(jLabelConstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jPasswordIngresarContraseña.setText("jPasswordField1");
        jPasswordIngresarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordIngresarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 30));

        jButtonAcceder.setBackground(new java.awt.Color(51, 255, 0));
        jButtonAcceder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 140, 40));

        jLabelFondoTaladro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taladro.jpg"))); // NOI18N
        jLabelFondoTaladro.setText("jLabel1");
        getContentPane().add(jLabelFondoTaladro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
      
    String usuarioIngresado = jTextFieldIngresarUsuario.getText();
    String contraseñaIngresada = new String(jPasswordIngresarContraseña.getPassword());  // Convertir a String la contraseña
    
    // Credenciales correctas (pueden ser verificadas desde una base de datos, archivo, etc.)
    String usuarioCorrecto = "admin"; // Usuario correcto
    String contraseñaCorrecta = "123"; // Contraseña correcta
    
        // Validación de campos vacíos
    if (usuarioIngresado.isEmpty() || contraseñaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  // Termina el método si hay campos vacíos
    }

    // Verificar si las credenciales son correctas
    if (usuarioIngresado.equals(usuarioCorrecto) && contraseñaIngresada.equals(contraseñaCorrecta)) {
        // Si las credenciales son correctas, proceder a acceder (por ejemplo, abrir otro formulario)
        JOptionPane.showMessageDialog(this, "Acceso correcto", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // Aquí, podrías abrir otro formulario si deseas
         //nuevoFormulario.setVisible(true);
         //this.dispose();  // Cerrar el formulario de login si lo deseas
        
    } else {
        // Si las credenciales son incorrectas, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        
        // Limpiar los campos para que el usuario intente nuevamente
        jTextFieldIngresarUsuario.setText("");
        jPasswordIngresarContraseña.setText("");
    } //d your handling code here:
    }//GEN-LAST:event_jButtonAccederActionPerformed

    private void jPasswordIngresarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordIngresarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordIngresarContraseñaActionPerformed

    private void jTextFieldIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelConstraseña;
    private javax.swing.JLabel jLabelControlAcceso;
    private javax.swing.JLabel jLabelFondoTaladro;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordIngresarContraseña;
    private javax.swing.JTextField jTextFieldIngresarUsuario;
    // End of variables declaration//GEN-END:variables
}
