/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sando
 */
public class IngresarPersonaform extends javax.swing.JFrame {

    /**
     * Creates new form IngresarPersonaform
     */
    public IngresarPersonaform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabelIngresarPersona = new javax.swing.JLabel();
        jLabelNombreCompleto = new javax.swing.JLabel();
        jTextFileIngresarNombre = new javax.swing.JTextField();
        jLabelTipoDeDocumento = new javax.swing.JLabel();
        jComboTiposDocumentos = new javax.swing.JComboBox<>();
        jLabelNumeroID = new javax.swing.JLabel();
        jTexttIngresarID = new javax.swing.JTextField();
        jCheckBoxRegistrarElemento = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jCheckBoxReigistrarVehiculo = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jLabelFondoTaladro = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 520));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIngresarPersona.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelIngresarPersona.setText("Ingresar Persona");
        jPanel1.add(jLabelIngresarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabelNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombreCompleto.setText("Nombre Completo");
        jPanel1.add(jLabelNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jTextFileIngresarNombre.setText("Apellidos y Nombres");
        jPanel1.add(jTextFileIngresarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 170, 30));

        jLabelTipoDeDocumento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTipoDeDocumento.setText("Tipo de documento ");
        jPanel1.add(jLabelTipoDeDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jComboTiposDocumentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de documento", "Cedula de ciudadania", "Pasaporte", "Tarjeta de Identidad" }));
        jComboTiposDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTiposDocumentosActionPerformed(evt);
            }
        });
        jPanel1.add(jComboTiposDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 170, 30));

        jLabelNumeroID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroID.setText("NumeroID");
        jPanel1.add(jLabelNumeroID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jTexttIngresarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttIngresarIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTexttIngresarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 170, 30));

        jCheckBoxRegistrarElemento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxRegistrarElemento.setText("Registrar elemento");
        jPanel1.add(jCheckBoxRegistrarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jTextField1.setText("Tipo de elemento");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, 30));

        jTextField2.setText("Serial o ID");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 130, 30));

        jCheckBoxReigistrarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBoxReigistrarVehiculo.setText("Registrar vehiculo");
        jCheckBoxReigistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReigistrarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxReigistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jTextField3.setText("Placa");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 130, 30));

        jLabelFondoTaladro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taladro.jpg"))); // NOI18N
        jLabelFondoTaladro.setText("jLabel1");
        jPanel1.add(jLabelFondoTaladro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTiposDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTiposDocumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTiposDocumentosActionPerformed

    private void jCheckBoxReigistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReigistrarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxReigistrarVehiculoActionPerformed

    private void jTexttIngresarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttIngresarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttIngresarIDActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarPersonaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarPersonaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarPersonaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarPersonaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IngresarPersonaform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxRegistrarElemento;
    private javax.swing.JCheckBox jCheckBoxReigistrarVehiculo;
    private javax.swing.JComboBox<String> jComboTiposDocumentos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondoTaladro;
    private javax.swing.JLabel jLabelIngresarPersona;
    private javax.swing.JLabel jLabelNombreCompleto;
    private javax.swing.JLabel jLabelNumeroID;
    private javax.swing.JLabel jLabelTipoDeDocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFileIngresarNombre;
    private javax.swing.JTextField jTexttIngresarID;
    // End of variables declaration//GEN-END:variables
}
