/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;


public class Lobby extends javax.swing.JFrame {
    

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonIngresarPersonas = new javax.swing.JButton();
        jButtonRegistros = new javax.swing.JButton();
        jButtonConsultas = new javax.swing.JButton();
        jLabelFondoTaladro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresarPersonas.setBackground(new java.awt.Color(255, 102, 0));
        jButtonIngresarPersonas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonIngresarPersonas.setText("Ingresar persona");
        jButtonIngresarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIngresarPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, 110));

        jButtonRegistros.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegistros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRegistros.setText("Registros ");
        jButtonRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 140, 110));

        jButtonConsultas.setBackground(new java.awt.Color(51, 204, 0));
        jButtonConsultas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonConsultas.setText("Consultas");
        jButtonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 140, 110));

        jLabelFondoTaladro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taladro.jpg"))); // NOI18N
        jLabelFondoTaladro.setText("jLabel1");
        jPanel1.add(jLabelFondoTaladro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 800, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarPersonasActionPerformed
  // Crear una instancia del formulario IngresarPersonaform
    IngresarPersonaform ingresarPersonaForm = new IngresarPersonaform();
    
    // Hacer visible el formulario
    ingresarPersonaForm.setVisible(true);
    }//GEN-LAST:event_jButtonIngresarPersonasActionPerformed

    private void jButtonRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrosActionPerformed
   // Crear una instancia del formulario RegistrosForm
    RegistrosForm registrosForm = new RegistrosForm();
    
    // Hacer visible el formulario
    registrosForm.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrosActionPerformed

    private void jButtonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultasActionPerformed
     ConsultasForm consultasForm = new ConsultasForm();
        new ConsultasForm().setVisible(true);
    }//GEN-LAST:event_jButtonConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Lobby().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonIngresarPersonas;
    private javax.swing.JButton jButtonRegistros;
    private javax.swing.JLabel jLabelFondoTaladro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
