/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author sando
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelControlAcceso = new javax.swing.JLabel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldIngresarUsuario = new javax.swing.JTextField();
        jLabelConstraseña = new javax.swing.JLabel();
        jPasswordIngresarContraseña = new javax.swing.JPasswordField();
        jButtonAcceder = new javax.swing.JButton();
        jLabelFondoTaladro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelControlAcceso.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabelControlAcceso.setText("Control Acceso Porteria");
        getContentPane().add(jLabelControlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabelBienvenido.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelBienvenido.setText("Bienvenido");
        getContentPane().add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jTextFieldIngresarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldIngresarUsuario.setText("Ingrese su usuario");
        jTextFieldIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIngresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 210, -1));

        jLabelConstraseña.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelConstraseña.setText("Contraseña");
        getContentPane().add(jLabelConstraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jPasswordIngresarContraseña.setText("jPasswordField1");
        jPasswordIngresarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordIngresarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordIngresarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 210, 30));

        jButtonAcceder.setBackground(new java.awt.Color(51, 255, 0));
        jButtonAcceder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAcceder.setText("Acceder");
        jButtonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 140, 40));

        jLabelFondoTaladro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taladro.jpg"))); // NOI18N
        jLabelFondoTaladro.setText("jLabel1");
        getContentPane().add(jLabelFondoTaladro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresarUsuarioActionPerformed

    private void jPasswordIngresarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordIngresarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordIngresarContraseñaActionPerformed

    private void jButtonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccederActionPerformed
            String usuarioIngresado = jTextFieldIngresarUsuario.getText();
    String contraseñaIngresada = new String(jPasswordIngresarContraseña.getPassword()); 

    // Validación de campos vacíos
    if (usuarioIngresado.isEmpty() || contraseñaIngresada.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
    }

    // Verificar credenciales en la base de datos
    LoginController loginController = new LoginController();
    boolean accesoPermitido = loginController.login(usuarioIngresado, contraseñaIngresada);

    if (accesoPermitido) {
        JOptionPane.showMessageDialog(this, "Acceso correcto", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Abrir el formulario Lobby
        Lobby lobbyForm = new Lobby();
        lobbyForm.setVisible(true);
        this.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        jTextFieldIngresarUsuario.setText("");
        jPasswordIngresarContraseña.setText("");
    }
    }//GEN-LAST:event_jButtonAccederActionPerformed

    public static void main(String args[]) {
    /* Establecer el tema Nimbus */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    /* Crear y mostrar la ventana */
     java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
          LoginForm login = new LoginForm();
          login.setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceder;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelConstraseña;
    private javax.swing.JLabel jLabelControlAcceso;
    private javax.swing.JLabel jLabelFondoTaladro;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordIngresarContraseña;
    private javax.swing.JTextField jTextFieldIngresarUsuario;
    // End of variables declaration//GEN-END:variables
}
